<?php

/**
 * Implements hook_menu().
 */
function crosswalk_menu() {
  $items['front'] = array(
    'title' => 'Crosswalk',
    'page callback' => 'crosswalk_frontpage',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function crosswalk_block_info() {
  $blocks['crosswalk_wide_page_title'] = array(
    'info' => t('Wide page title'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implmeents hook_block_view().
 */
function crosswalk_block_view($delta = '') {
  switch ($delta) {
    case 'crosswalk_wide_page_title' :
      $block['content'] = crosswalk_wide_page_title_block();
    break;
  }

  return $block;
}

/**
 * Callback function for the Wide page title crosswalk block.
 */
function crosswalk_wide_page_title_block() {
  $menu = menu_get_item();

  $content = array(
    '#markup' => $menu['title'],
  );

  return $content;
}


/**
 * Page callback for /front
 *
 * Provides a blank page we can use to hang a context on.
 */
function crosswalk_frontpage() {
  return '';
}

/**
 * Implements preprocess_block().
 */
function crosswalk_preprocess_block(&$vars) {
  if ($vars['block_html_id'] == 'block-views-what-is-crosswalk-block') {
    $vars['classes_array'] = array('what-is-crosswalk');
  }

  if ($vars['block_html_id'] == 'block-views-blog-listing-block-1') {
    $vars['classes_array'] = array('recent-blog-entries');
  }
}

/**
 * Implements preprocess_node().
 */
function crosswalk_preprocess_node(&$vars) {
  // On page nodes we want to display the node title in another region
  // via a block. This variable will hide the node title from the node template.
  $vars['wide_page_title'] = ($vars['type'] == 'page') ? TRUE : FALSE;
}

